nav:
  display_title: true
  display_post_title: true
  fixed: false
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  关于: /about/ || fas fa-user
social:
  fab fa-github: https://github.com/Carri1Sun || GitHub || '#24292e'
favicon: /img/fluid.png
avatar:
  img: /img/avatar.png
  effect: false
disable_top_img: false
default_top_img: /img/default.png
index_img: /img/default.png
index_top_img_height: 76vh
archive_img: /img/default.png
background: "#f4f5f9"
cover:
  index_enable: false
  aside_enable: false
  archives_enable: false
subtitle:
  enable: true
  effect: true
  source: false
  sub:
    - 在产品、工程与 Agent 之间，持续把问题想清楚。
index_layout: 4
index_post_content:
  method: 2
  length: 260
post_copyright:
  enable: false
footer:
  owner:
    enable: true
    since: 2026
  custom_text: Kaiyi's Notes
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
